# Data Cleaning

In [14]:
# Dropping Irrelevent Columns
# Handling Missing Values
# Type-Convertion
# Handling Duplicates
# Outlier Detection
# Fixing the inconsistent data
# Dealing with time related columns (datetime)

In [15]:
## Execute all the ways to clean your data(on a sample dataset) - Data Cleaning Task-1

In [16]:
import pandas as pd

In [17]:
df1 = pd.read_excel('/content/Customer Call List (1) (1).xlsx')
df1

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [18]:
df = df1.copy()
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [19]:
# Re-assign
# inplace = True
# df = df.drop..........

In [20]:
df = df.drop(columns=['Not_Useful_Column'])
# axis=0 -> rows
# axis=1 -> columns

In [21]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [22]:
# Handling Duplicates
df.duplicated().sum()

np.int64(1)

In [23]:
df = df.drop_duplicates()

# Janavi  MCA
# Pooja   BCA
# Rini    BE
# Janavi  MCA
# Janavi  MCA

In [24]:
df #

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [25]:
# Deal with Last Name
df
# Char(... / _)
df['Last_Name'] = df['Last_Name'].str.strip('.../_')


# RESULT
#"../Smith_/"  →  "Smith"
#"..._Doe..."  →  "Doe"
#"///Lee"      →  "Lee"
#"Taylor_/"    →  "Taylor"

/tmp/ipykernel_4607/1783652681.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Last_Name'] = df['Last_Name'].str.strip('.../_')

In [26]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [28]:
df['Phone_Number'] = df['Phone_Number'].astype(str)

/tmp/ipykernel_4607/3709584489.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Phone_Number'] = df['Phone_Number'].astype(str)

In [29]:
df['Phone_Number'] = df['Phone_Number'].replace('\D','', regex=True)

# \D -> Non Digit
# regex = regular expression

# 123-456-7890
#1 2 3 - 4 5 6 - 7 8 9 0
# 1 2 3 4 5 6 7 8 9 0

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
/tmp/ipykernel_4607/3578739405.py:1: SyntaxWarning: invalid escape sequence '\D'
  df['Phone_Number'] = df['Phone_Number'].replace('\D','', regex=True)
/tmp/ipykernel_4607/3578739405.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Phone_Number'] = df['Phone_Number'].replace('\D','', regex=True)

In [30]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street,City,Zip_Code
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,1236439775,93 West Main Street,No,Yes,93 West Main Street,None,None
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,3047622467,768 City Parkway,Yes,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,,1209 South Street,No,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,No,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Yes,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,612 Shire Lane,Shire,None
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,1235432345,2039 Main Street,Yes,N,2039 Main Street,None,None
13,1014,Leslie,Knope,8766783469,343 City Parkway,Yes,No,343 City Parkway,None,None
14,1015,Toby,Flenderson,3047622467,214 HR Avenue,N,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,No,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,N/a,Yes,N/a,None,None
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine,None

In [31]:
# Dealing with Address
df[['Street', 'City', 'Zip_Code']] = df['Address'].str.split(',',n=2, expand=True)
df

#      Address
#Street, City, Zip_Code

/tmp/ipykernel_4607/2139991227.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['Street', 'City', 'Zip_Code']] = df['Address'].str.split(',',n=2, expand=True)

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street,City,Zip_Code
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,1236439775,93 West Main Street,No,Yes,93 West Main Street,None,None
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,3047622467,768 City Parkway,Yes,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,,1209 South Street,No,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,No,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Yes,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,612 Shire Lane,Shire,None
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,1235432345,2039 Main Street,Yes,N,2039 Main Street,None,None
13,1014,Leslie,Knope,8766783469,343 City Parkway,Yes,No,343 City Parkway,None,None
14,1015,Toby,Flenderson,3047622467,214 HR Avenue,N,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,No,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,N/a,Yes,N/a,None,None
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine,None

In [32]:
df = df.drop(columns=['Address'])
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street,City,Zip_Code
0,1001,Frodo,Baggins,1235455421,Yes,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,1236439775,No,Yes,93 West Main Street,None,None
2,1003,Walter,White,7066950392,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,1235432345,Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,8766783469,Y,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,3047622467,Yes,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,,No,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,8766783469,N,No,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,Yes,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,1235455421,Yes,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,Yes,No,612 Shire Lane,Shire,None
11,1012,Harry,Potter,7066950392,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,1235432345,Yes,N,2039 Main Street,None,None
13,1014,Leslie,Knope,8766783469,Yes,No,343 City Parkway,None,None
14,1015,Toby,Flenderson,3047622467,N,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,1235455421,No,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,1236439775,Yes,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,7066950392,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,Yes,N/a,None,None
19,1020,Anakin,Skywalker,8766783469,Yes,N,910 Tatooine Road,Tatooine,None

In [33]:
# Dealing with Paying Customer
df['Paying Customer'] = df['Paying Customer'].str.replace('Yes','Y').str.replace('No','N')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street,City,Zip_Code
0,1001,Frodo,Baggins,1235455421,Y,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,1236439775,N,Yes,93 West Main Street,None,None
2,1003,Walter,White,7066950392,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,1235432345,Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,8766783469,Y,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,3047622467,Y,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,,N,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,8766783469,N,No,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,Y,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,1235455421,Y,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,Y,No,612 Shire Lane,Shire,None
11,1012,Harry,Potter,7066950392,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,1235432345,Y,N,2039 Main Street,None,None
13,1014,Leslie,Knope,8766783469,Y,No,343 City Parkway,None,None
14,1015,Toby,Flenderson,3047622467,N,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,1235455421,N,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,1236439775,Y,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,7066950392,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,Yes,N/a,None,None
19,1020,Anakin,Skywalker,8766783469,Y,N,910 Tatooine Road,Tatooine,None

In [34]:
# Dealing with Do_Not_Contact
df['Do_Not_Contact'] = df['Do_Not_Contact'].str.replace('Yes','Y').str.replace('No','N')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street,City,Zip_Code
0,1001,Frodo,Baggins,1235455421,Y,N,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,1236439775,N,Y,93 West Main Street,None,None
2,1003,Walter,White,7066950392,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,1235432345,Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,8766783469,Y,N,123 Dragons Road,None,None
5,1006,Ron,Swanson,3047622467,Y,Y,768 City Parkway,None,None
6,1007,Jeff,Winger,,N,N,1209 South Street,None,None
7,1008,Sherlock,Holmes,8766783469,N,N,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,Y,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,1235455421,Y,N,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,Shire,None
11,1012,Harry,Potter,7066950392,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,1235432345,Y,N,2039 Main Street,None,None
13,1014,Leslie,Knope,8766783469,Y,N,343 City Parkway,None,None
14,1015,Toby,Flenderson,3047622467,N,N,214 HR Avenue,None,None
15,1016,Ron,Weasley,1235455421,N,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,1236439775,Y,N,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,7066950392,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,Y,N/a,None,None
19,1020,Anakin,Skywalker,8766783469,Y,N,910 Tatooine Road,Tatooine,None

In [ ]:
df['Paying Customer'] = df['Paying Customer'].replace('N/a','')

df['Paying Customer'] = df['Paying Customer'].fillna('')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street,City,Zip_Code
0,1001,Frodo,Baggins,1235455421,Y,N,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,1236439775,N,Y,93 West Main Street,None,None
2,1003,Walter,White,7066950392,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,1235432345,Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,8766783469,Y,N,123 Dragons Road,None,None
5,1006,Ron,Swanson,3047622467,Y,Y,768 City Parkway,None,None
6,1007,Jeff,Winger,,N,N,1209 South Street,None,None
7,1008,Sherlock,Holmes,8766783469,N,N,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,Y,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,1235455421,Y,N,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,Shire,None
11,1012,Harry,Potter,7066950392,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,1235432345,Y,N,2039 Main Street,None,None
13,1014,Leslie,Knope,8766783469,Y,N,343 City Parkway,None,None
14,1015,Toby,Flenderson,3047622467,N,N,214 HR Avenue,None,None
15,1016,Ron,Weasley,1235455421,N,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,1236439775,Y,N,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,7066950392,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,,Y,N/a,None,None
20,1020,Anakin,Skywalker,8766783469,Y,N,910 Tatooine Road,Tatooine,None

In [ ]:
df['Do_Not_Contact'] = df['Do_Not_Contact'].fillna('')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street,City,Zip_Code
0,1001,Frodo,Baggins,1235455421,Y,N,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,1236439775,N,Y,93 West Main Street,None,None
2,1003,Walter,White,7066950392,N,,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,1235432345,Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,8766783469,Y,N,123 Dragons Road,None,None
5,1006,Ron,Swanson,3047622467,Y,Y,768 City Parkway,None,None
6,1007,Jeff,Winger,,N,N,1209 South Street,None,None
7,1008,Sherlock,Holmes,8766783469,N,N,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,Y,,123 Middle Earth,None,None
9,1010,Peter,Parker,1235455421,Y,N,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,Shire,None
11,1012,Harry,Potter,7066950392,Y,,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,1235432345,Y,N,2039 Main Street,None,None
13,1014,Leslie,Knope,8766783469,Y,N,343 City Parkway,None,None
14,1015,Toby,Flenderson,3047622467,N,N,214 HR Avenue,None,None
15,1016,Ron,Weasley,1235455421,N,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,1236439775,Y,N,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,7066950392,Y,,3498 Super Lane,None,None
18,1019,Creed,Braton,,,Y,N/a,None,None
20,1020,Anakin,Skywalker,8766783469,Y,N,910 Tatooine Road,Tatooine,None

In [ ]:
df2 = df.copy()
df2

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street,City,Zip_Code
0,1001,Frodo,Baggins,1235455421,Y,N,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,1236439775,N,Y,93 West Main Street,None,None
2,1003,Walter,White,7066950392,N,,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,1235432345,Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,8766783469,Y,N,123 Dragons Road,None,None
5,1006,Ron,Swanson,3047622467,Y,Y,768 City Parkway,None,None
6,1007,Jeff,Winger,,N,N,1209 South Street,None,None
7,1008,Sherlock,Holmes,8766783469,N,N,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,Y,,123 Middle Earth,None,None
9,1010,Peter,Parker,1235455421,Y,N,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,Shire,None
11,1012,Harry,Potter,7066950392,Y,,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,1235432345,Y,N,2039 Main Street,None,None
13,1014,Leslie,Knope,8766783469,Y,N,343 City Parkway,None,None
14,1015,Toby,Flenderson,3047622467,N,N,214 HR Avenue,None,None
15,1016,Ron,Weasley,1235455421,N,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,1236439775,Y,N,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,7066950392,Y,,3498 Super Lane,None,None
18,1019,Creed,Braton,,,Y,N/a,None,None
20,1020,Anakin,Skywalker,8766783469,Y,N,910 Tatooine Road,Tatooine,None

In [ ]:
df2 = df2[df2['Do_Not_Contact'] != 'Y']
df2

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street,City,Zip_Code
0,1001,Frodo,Baggins,1235455421,Y,N,123 Shire Lane,Shire,None
2,1003,Walter,White,7066950392,N,,298 Drugs Driveway,None,None
4,1005,Jon,Snow,8766783469,Y,N,123 Dragons Road,None,None
6,1007,Jeff,Winger,,N,N,1209 South Street,None,None
7,1008,Sherlock,Holmes,8766783469,N,N,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,Y,,123 Middle Earth,None,None
9,1010,Peter,Parker,1235455421,Y,N,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,Shire,None
11,1012,Harry,Potter,7066950392,Y,,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,1235432345,Y,N,2039 Main Street,None,None
13,1014,Leslie,Knope,8766783469,Y,N,343 City Parkway,None,None
14,1015,Toby,Flenderson,3047622467,N,N,214 HR Avenue,None,None
15,1016,Ron,Weasley,1235455421,N,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,1236439775,Y,N,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,7066950392,Y,,3498 Super Lane,None,None
20,1020,Anakin,Skywalker,8766783469,Y,N,910 Tatooine Road,Tatooine,None

In [ ]:
for x in df.index:
  if df.loc[x, 'Do_Not_Contact'] == 'Y':
    df.drop(x, inplace=True)

df

# df2 = df2[df2['Do_Not_Contact'] != 'Y']
# df2

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street,City,Zip_Code
0,1001,Frodo,Baggins,1235455421,Y,N,123 Shire Lane,Shire,None
2,1003,Walter,White,7066950392,N,,298 Drugs Driveway,None,None
4,1005,Jon,Snow,8766783469,Y,N,123 Dragons Road,None,None
6,1007,Jeff,Winger,,N,N,1209 South Street,None,None
7,1008,Sherlock,Holmes,8766783469,N,N,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,Y,,123 Middle Earth,None,None
9,1010,Peter,Parker,1235455421,Y,N,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,Shire,None
11,1012,Harry,Potter,7066950392,Y,,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,1235432345,Y,N,2039 Main Street,None,None
13,1014,Leslie,Knope,8766783469,Y,N,343 City Parkway,None,None
14,1015,Toby,Flenderson,3047622467,N,N,214 HR Avenue,None,None
15,1016,Ron,Weasley,1235455421,N,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,1236439775,Y,N,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,7066950392,Y,,3498 Super Lane,None,None
20,1020,Anakin,Skywalker,8766783469,Y,N,910 Tatooine Road,Tatooine,None

In [ ]:
df = df.drop_duplicates(subset=['Phone_Number'])
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street,City,Zip_Code
0,1001,Frodo,Baggins,1235455421,Y,N,123 Shire Lane,Shire,None
1,1003,Walter,White,7066950392,N,,298 Drugs Driveway,None,None
2,1005,Jon,Snow,8766783469,Y,N,123 Dragons Road,None,None
3,1007,Jeff,Winger,,N,N,1209 South Street,None,None
9,1013,Don,Draper,1235432345,Y,N,2039 Main Street,None,None
11,1015,Toby,Flenderson,3047622467,N,N,214 HR Avenue,None,None
13,1017,Michael,Scott,1236439775,Y,N,121 Paper Avenue,Pennsylvania,None

In [ ]:
df = df.drop(df[df['Phone_Number'] == ''].index)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street,City,Zip_Code
0,1001,Frodo,Baggins,1235455421,Y,N,123 Shire Lane,Shire,None
1,1003,Walter,White,7066950392,N,,298 Drugs Driveway,None,None
2,1005,Jon,Snow,8766783469,Y,N,123 Dragons Road,None,None
9,1013,Don,Draper,1235432345,Y,N,2039 Main Street,None,None
11,1015,Toby,Flenderson,3047622467,N,N,214 HR Avenue,None,None
13,1017,Michael,Scott,1236439775,Y,N,121 Paper Avenue,Pennsylvania,None

In [ ]:
df = df.reset_index(drop=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street,City,Zip_Code
0,1001,Frodo,Baggins,1235455421,Y,N,123 Shire Lane,Shire,None
1,1003,Walter,White,7066950392,N,,298 Drugs Driveway,None,None
2,1005,Jon,Snow,8766783469,Y,N,123 Dragons Road,None,None
3,1013,Don,Draper,1235432345,Y,N,2039 Main Street,None,None
4,1015,Toby,Flenderson,3047622467,N,N,214 HR Avenue,None,None
5,1017,Michael,Scott,1236439775,Y,N,121 Paper Avenue,Pennsylvania,None

In [35]:
df.to_excel('Cleaned_Customer_Call_List.xlsx', index=False)

In [36]:
c_df = pd.read_excel('/content/Cleaned_Customer_Call_List.xlsx')
c_df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street,City,Zip_Code
0,1001,Frodo,Baggins,1.235455e+09,Y,N,123 Shire Lane,Shire,NaN
1,1002,Abed,Nadir,1.236440e+09,N,Y,93 West Main Street,NaN,NaN
2,1003,Walter,White,7.066950e+09,N,NaN,298 Drugs Driveway,NaN,NaN
3,1004,Dwight,Schrute,1.235432e+09,Y,Y,980 Paper Avenue,Pennsylvania,18503.0
4,1005,Jon,Snow,8.766783e+09,Y,N,123 Dragons Road,NaN,NaN
5,1006,Ron,Swanson,3.047622e+09,Y,Y,768 City Parkway,NaN,NaN
6,1007,Jeff,Winger,NaN,N,N,1209 South Street,NaN,NaN
7,1008,Sherlock,Holmes,8.766783e+09,N,N,98 Clue Drive,NaN,NaN
8,1009,Gandalf,NaN,NaN,Y,NaN,123 Middle Earth,NaN,NaN
9,1010,Peter,Parker,1.235455e+09,Y,N,25th Main Street,New York,NaN
10,1011,Samwise,Gamgee,NaN,Y,N,612 Shire Lane,Shire,NaN
11,1012,Harry,Potter,7.066950e+09,Y,NaN,2394 Hogwarts Avenue,NaN,NaN
12,1013,Don,Draper,1.235432e+09,Y,N,2039 Main Street,NaN,NaN
13,1014,Leslie,Knope,8.766783e+09,Y,N,343 City Parkway,NaN,NaN
14,1015,Toby,Flenderson,3.047622e+09,N,N,214 HR Avenue,NaN,NaN
15,1016,Ron,Weasley,1.235455e+09,N,N,2395 Hogwarts Avenue,NaN,NaN
16,1017,Michael,Scott,1.236440e+09,Y,N,121 Paper Avenue,Pennsylvania,NaN
17,1018,Clark,Kent,7.066950e+09,Y,NaN,3498 Super Lane,NaN,NaN
18,1019,Creed,Braton,NaN,N/a,Y,N/a,NaN,NaN
19,1020,Anakin,Skywalker,8.766783e+09,Y,N,910 Tatooine Road,Tatooine,NaN